name: flutter_convert_wav_to_m4a
description: Convert WAV to M4A using FFmpeg WASM in Flutter Web
version: 0.0.1
homepage: https://github.com/vuduchiieu/flutter_convert_wav_to_m4a
repository: https://github.com/vuduchiieu/flutter_convert_wav_to_m4a
issue_tracker: https://github.com/vuduchiieu/flutter_convert_wav_to_m4a/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterConvertWavToM4aWeb
        fileName: flutter_convert_wav_to_m4a_web.dart
#flutter pub publish
